-- Create and use the database
CREATE DATABASE university_events;
USE university_events;

-- Create events table with all required columns
CREATE TABLE events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    start_time TIME NOT NULL,
    venue VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    faculty VARCHAR(100) NOT NULL DEFAULT 'All Faculties'
);

-- Insert all university events
INSERT INTO events (title, start_date, start_time, venue, description, faculty) VALUES
('University Orientation Day', '2024-01-15', '09:00:00', 'Main Auditorium', 
 'Welcome orientation for new students with campus tour and department introductions.', 'All Faculties'),
('Science Fair 2024', '2025-02-01', '10:00:00', 'Science Building', 
 'Annual science fair showcasing student research projects and innovations.', 'Computing & Technology'),
('Career Fair', '2025-02-15', '11:00:00', 'Student Center', 
 'Meet representatives from top companies and explore career opportunities.', 'All Faculties'),
('Alumni Meet', '2025-03-01', '14:00:00', 'Conference Hall', 
 'Annual alumni gathering with networking opportunities and guest speeches.', 'All Faculties'),
('Sports Day', '2025-03-15', '08:00:00', 'University Stadium', 
 'Annual sports competition featuring various athletic events.', 'Social Sciences'),
('Programming Contest', '2024-04-01', '09:30:00', 'Computer Lab', 
 'Coding competition for students to showcase their programming skills.', 'Medicine'),
('Art Exhibition', '2025-04-15', '13:00:00', 'Art Gallery', 
 'Student art showcase featuring paintings, sculptures, and digital art.', 'Commerce & Management'),
('Music Festival', '2025-05-01', '16:00:00', 'Open Air Theater', 
 'Annual music festival featuring student bands and professional performers.', 'Computing & Technology'),
('Research Symposium', '2025-05-15', '10:00:00', 'Research Center', 
 'Presentation of research papers by faculty and graduate students.', 'All Faculties'),
('Graduation Ceremony', '2025-06-01', '09:00:00', 'Main Stadium', 
 'Annual graduation ceremony for the Class of 2024.', 'Computing & Technology'),
('Technology Workshop', '2025-06-15', '11:00:00', 'Tech Hub', 
 'Hands-on workshop on emerging technologies and their applications.', 'Commerce & Management'),
('Literary Festival', '2025-07-01', '14:00:00', 'Library Complex', 
 'Celebration of literature with book readings and author discussions.', 'Medicine'),
('Environmental Day', '2025-07-15', '09:00:00', 'Botanical Garden', 
 'Activities promoting environmental awareness and sustainability.', 'Computing & Technology'),
('Innovation Summit', '2025-08-01', '10:00:00', 'Innovation Center', 
 'Showcase of innovative projects and startup ideas by students.', 'Social Sciences'),
('Cultural Day', '2025-08-15', '12:00:00', 'Cultural Center', 
 'Celebration of diverse cultures through performances and exhibitions.', 'Commerce & Management'),
('Math Olympiad', '2025-09-01', '09:00:00', 'Mathematics Building', 
 'Mathematics competition for undergraduate students.', 'Computing & Technology'),
('Debate Competition', '2025-09-15', '13:00:00', 'Debate Hall', 
 'Inter-university debate competition on contemporary topics.', 'All Faculties'),
('Film Festival', '2025-10-01', '15:00:00', 'Media Center', 
 'Screening of student-made films and documentaries.', 'Commerce & Management'),
('Robotics Exhibition', '2025-10-15', '10:00:00', 'Engineering Block', 
 'Display of robotic projects and automation solutions.', 'Commerce & Management'),
('Year-End Concert', '2025-11-01', '18:00:00', 'Concert Hall', 
 'Grand musical performance featuring university orchestra and choir.', 'Commerce & Management'),
('Business Analytics Workshop', '2025-11-15', '09:00:00', 'Business School', 
 'Workshop on data analytics tools and business intelligence.', 'Commerce & Management'),
('Medical Conference', '2025-11-30', '08:30:00', 'Medical Center', 
 'International conference on recent advances in medicine.', 'Medicine'),
('AI Symposium', '2025-12-05', '10:00:00', 'Tech Center', 
 'Discussion on artificial intelligence and its impact on society.', 'Computing & Technology'),
('Winter Music Concert', '2025-12-15', '17:00:00', 'Music Hall', 
 'Seasonal concert featuring classical and contemporary music.', 'All Faculties'),
('Entrepreneurship Summit', '2026-01-10', '09:30:00', 'Business Center', 
 'Summit focusing on startup ecosystem and entrepreneurship.', 'Commerce & Management'),
('Psychology Conference', '2026-01-20', '10:00:00', 'Psychology Department', 
 'Conference on behavioral psychology and mental health.', 'Social Sciences'),
('Digital Art Exhibition', '2026-02-05', '11:00:00', 'Digital Studio', 
 'Exhibition of digital artworks and multimedia installations.', 'Computing & Technology'),
('Leadership Workshop', '2026-02-20', '09:00:00', 'Management Block', 
 'Workshop on developing leadership skills and team management.', 'Commerce & Management'),
('Healthcare Innovation Forum', '2026-03-05', '10:30:00', 'Health Sciences Building', 
 'Forum discussing innovations in healthcare delivery.', 'Medicine'),
('International Food Festival', '2026-03-15', '12:00:00', 'University Plaza', 
 'Celebration of international cuisines and cultural exchange.', 'All Faculties'),
('Cybersecurity Conference', '2026-03-30', '09:00:00', 'Security Lab', 
 'Conference on latest trends in cybersecurity and data protection.', 'Computing & Technology'),
('Spring Theater Production', '2026-04-10', '18:00:00', 'Theater Hall', 
 'Student theater group presenting a classical play.', 'Social Sciences'),
('Data Science Day', '2026-04-25', '10:00:00', 'Computing Center', 
 'Workshops and presentations on data science applications.', 'Computing & Technology'),
('Economics Forum', '2026-05-05', '09:30:00', 'Economics Department', 
 'Discussion on global economic trends and policies.', 'Commerce & Management'),
('Health and Wellness Fair', '2026-05-20', '09:00:00', 'Sports Complex', 
 'Fair promoting physical and mental wellness activities.', 'Medicine'),
('Mobile App Challenge', '2026-06-05', '10:00:00', 'Innovation Lab', 
 'Competition for developing innovative mobile applications.', 'Computing & Technology'),
('Photography Exhibition', '2026-06-20', '13:00:00', 'Art Center', 
 'Exhibition of student and professional photography.', 'All Faculties'),
('Finance Summit', '2026-07-05', '09:00:00', 'Finance Lab', 
 'Summit on financial markets and investment strategies.', 'Commerce & Management'),
('Medical Ethics Symposium', '2026-07-20', '10:30:00', 'Ethics Center', 
 'Discussion on ethical issues in medical practice.', 'Medicine'),
('Game Development Workshop', '2026-08-05', '11:00:00', 'Gaming Lab', 
 'Hands-on workshop on video game development.', 'Computing & Technology'),
('Social Impact Conference', '2026-08-20', '09:30:00', 'Social Sciences Building', 
 'Conference on social innovation and community impact.', 'Social Sciences'),
('Blockchain Technology Forum', '2026-09-05', '10:00:00', 'Technology Center', 
 'Forum on blockchain applications and cryptocurrency.', 'Computing & Technology'),
('Marketing Summit', '2026-09-20', '09:00:00', 'Marketing Lab', 
 'Summit on digital marketing and brand management.', 'Commerce & Management'),
('Medical Research Day', '2026-10-05', '08:30:00', 'Research Wing', 
 'Presentation of latest medical research findings.', 'Medicine'),
('Virtual Reality Exhibition', '2026-10-20', '11:00:00', 'VR Lab', 
 'Showcase of virtual reality projects and applications.', 'Computing & Technology'),
('Human Resources Conference', '2026-11-05', '09:30:00', 'HR Department', 
 'Conference on modern HR practices and workplace culture.', 'Commerce & Management'),
('Psychology Research Symposium', '2026-11-20', '10:00:00', 'Psychology Lab', 
 'Symposium on recent advances in psychological research.', 'Social Sciences'),
('Cloud Computing Workshop', '2026-12-05', '09:00:00', 'Cloud Lab', 
 'Workshop on cloud technologies and services.', 'Computing & Technology'),
('Year-End Research Showcase', '2026-12-20', '10:30:00', 'Research Complex', 
 'Exhibition of research projects from all departments.', 'All Faculties');
